
#
# Configuration file for Travis CI
# http://travis-ci.org/
#

language: java

jdk:
  - oraclejdk8

before_install:
  - git clone https://github.com/julianmendez/jcel.git
  - cd jcel
  - mvn clean install

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=false -B -V

after_success:
  - mvn clean cobertura:cobertura coveralls:report

sudo: false


